name: Run rp_handler

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r builder/requirements.txt

      - name: Run rp_handler.py
        run: |
          python src/rp_handler.py --test_input='{"input": {"prompt": "A happy place."}}'
