name: Run rp_handler

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r builder/requirements.txt

      - name: Set environment variables
        run: |
          echo "PYTHONDONTWRITEBYTECODE=1" >> $GITHUB_ENV
          echo "PYTHONBUFFERED=1" >> $GITHUB_ENV
          echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
          echo "RUNPOD_DEBUG_LEVEL=DEBUG" >> $GITHUB_ENV

      - name: Install Packages
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
          wget \
          libgl1-mesa-glx \
          libglib2.0-0

      - name: Grab Model
        run: |
          python builder/model_fetcher.py

      - name: Run rp_handler.py
        run: |
          python src/rp_handler.py --test_input='{"input": {"prompt": "A happy place."}}'
